/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestAdRouteImport } from './routes/test-ad'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolToolRouteImport } from './routes/tool.$tool'

const TestAdRoute = TestAdRouteImport.update({
  id: '/test-ad',
  path: '/test-ad',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolToolRoute = ToolToolRouteImport.update({
  id: '/tool/$tool',
  path: '/tool/$tool',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/test-ad': typeof TestAdRoute
  '/tool/$tool': typeof ToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/test-ad': typeof TestAdRoute
  '/tool/$tool': typeof ToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/test-ad': typeof TestAdRoute
  '/tool/$tool': typeof ToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/test-ad' | '/tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/test-ad' | '/tool/$tool'
  id: '__root__' | '/' | '/settings' | '/test-ad' | '/tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  TestAdRoute: typeof TestAdRoute
  ToolToolRoute: typeof ToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-ad': {
      id: '/test-ad'
      path: '/test-ad'
      fullPath: '/test-ad'
      preLoaderRoute: typeof TestAdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$tool': {
      id: '/tool/$tool'
      path: '/tool/$tool'
      fullPath: '/tool/$tool'
      preLoaderRoute: typeof ToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  TestAdRoute: TestAdRoute,
  ToolToolRoute: ToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
